server:
  port: 8082
spring:
  application:
    name: activity-service
  datasource:
    url: jdbc:h2:mem:activity
    username: sa
    password: p
    driver-class-name: org.h2.Driver
  rabbitmq:
    host: RABBIT-SERVER
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
