spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: activity
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/activity/**
  application:
    name: gateway-service
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
